[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/challenge-submissions"
  to = "/.netlify/functions/challenge-submissions"
  status = 200
  force = true

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
  force = true
